### ISSUE TITLE
Extend NFS Client to add mounts

### ISSUE THREAD

**Issue by td512** [ShellManager/roles#10]
Much like #9, we need to extend the NFS client play to allow automated provisioning of client mountpoints.

**Comment by td512** [comment]
This one's also relatively simple @Keanu73. I was thinking along the lines of `server` for the server's IP, `path` for the path, and `mountopts` for the mount options

**Comment by keanucz** [comment]
#12 adds that

**Comment by td512** [comment]
@Keanu73 might want to check which branch you're merging into

**Comment by td512** [comment]
I've updated the nfs-client branch. #11 fixes this
